# Generated by Django 4.2.5 on 2024-03-18 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogtable',
            name='firstname',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='blogtable',
            name='lastname',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
