# Generated by Django 4.2.5 on 2024-04-08 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogapp', '0002_blogtable_firstname_blogtable_lastname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogtable',
            name='image',
            field=models.ImageField(default='noimage.jpg', upload_to=''),
        ),
    ]
